export const IMAGES = {
  SPLASH_BACKGROUND: require('../assets/images/background.jpeg'),
  KPA_IMAGE: require('../assets/images/kpalogo.png'),
  LOGIN_BACKGROUND: require('../assets/images/login_background.jpeg'),
  WHATSAPP_IMAGE: require('../assets/images/whatsapp.jpeg'),
  EYE_CLOSE: require('../assets/images/eye.png'),
  EYE_OPEN: require('../assets/images/Vector.png'),
  LogIN_IMAGE: require('../assets/images/login.png'),
  BACKGROUND_IMAGE: require('../assets/images/backimg.jpeg'),
  SIGN_UP_BACKGROUND: require('../assets/images/signupback.jpeg'),
  USER: require('../assets/images/user.png'),
  IN_VISIBLE: require('../assets/images/invisible.png'),
  EDIT_PROFILE: require('../assets/images/pencil.png'),
  USER_IMAGE: require('../assets/images/userImage.png'),
  LIKE_IMAGE: require('../assets/images/like.png'),
  SETTING_IMAGE: require('../assets/images/settings.png'),
  BACK_IMAGE: require('../assets/images/BackImage.png'),
  CHAT_BACKGROUND: require('../assets/images/chatbackground.png'),
  VEDIO_IMAGE: require('../assets/images/video.png'),
  PHONE_IMAGE: require('../assets/images/phone.png'),
  LINES_IMAGE: require('../assets/images/lines.png'),
  ARROW_IMAGE: require('../assets/images/arrow.png'),
  ALLUSER_IMAGE: require('../assets/images/comment.png'),
};
